"""Tests for §6.2 Goal — including the ADR-018 single-parent-tree invariant."""
import pytest
from pydantic import ValidationError

from contracts.goal import Goal
from contracts.enums import GoalType, GoalStatus, Priority


def _goal(**overrides):
    defaults = dict(type=GoalType.PROJECT, title="Build Jarvis", mission_id="mission-1")
    defaults.update(overrides)
    return Goal(**defaults)


def test_minimal_goal_constructs():
    g = _goal()
    assert g.status == GoalStatus.DRAFT
    assert g.priority == Priority.MEDIUM
    assert g.parent_goal_id is None
    assert g.dependencies == []


def test_goal_cannot_be_its_own_parent():
    # Constructing then attempting self-reference requires a two-step
    # check since id is generated by default_factory; force it explicitly.
    g = _goal()
    with pytest.raises(ValidationError):
        Goal(
            id=g.id,
            type=GoalType.TASK,
            title="Self-parented",
            mission_id="mission-1",
            parent_goal_id=g.id,
        )


def test_goal_cannot_depend_on_itself():
    g = _goal()
    with pytest.raises(ValidationError):
        Goal(
            id=g.id,
            type=GoalType.TASK,
            title="Self-dependent",
            mission_id="mission-1",
            dependencies=[g.id],
        )


def test_single_parent_only_by_schema_shape():
    # ADR-018 (decision #4): parent_goal_id is a single scalar, not a list —
    # the schema itself makes multi-parent graphs structurally impossible,
    # which is the point (supersedes old Goals.md G-02).
    g = _goal(parent_goal_id="life-goal-1")
    assert isinstance(g.parent_goal_id, str)


def test_every_goal_requires_a_mission_id():
    with pytest.raises(ValidationError):
        Goal(type=GoalType.TASK, title="Orphan task")
